"""Settings module - 언어/테마 설정"""

# ═══════════ LANGUAGES ═══════════
LANGUAGES = {
    'ko':'한국어','en':'English','ja':'日本語','zh':'中文','es':'Español',
    'fr':'Français','de':'Deutsch','pt':'Português','ru':'Русский','vi':'Tiếng Việt',
}

# ═══════════ THEMES ═══════════
THEME_META = {
    'dark_purple':{'ko':'다크 퍼플','en':'Dark Purple','ja':'ダークパープル','zh':'暗紫色','es':'Púrpura Oscuro','fr':'Violet Foncé','de':'Dunkellila','pt':'Roxo Escuro','ru':'Тёмно-фиолет.','vi':'Tím đậm'},
    'light':{'ko':'라이트','en':'Light','ja':'ライト','zh':'浅色','es':'Claro','fr':'Clair','de':'Hell','pt':'Claro','ru':'Светлая','vi':'Sáng'},
    'dark_blue':{'ko':'다크 블루','en':'Dark Blue','ja':'ダークブルー','zh':'深蓝','es':'Azul Oscuro','fr':'Bleu Foncé','de':'Dunkelblau','pt':'Azul Escuro','ru':'Тёмно-синяя','vi':'Xanh đậm'},
    'nord':{'ko':'노드','en':'Nord','ja':'ノルド','zh':'北欧','es':'Nord','fr':'Nord','de':'Nord','pt':'Nord','ru':'Норд','vi':'Nord'},
    'rose':{'ko':'로즈','en':'Rosé','ja':'ローズ','zh':'玫瑰','es':'Rosa','fr':'Rose','de':'Rosé','pt':'Rosa','ru':'Розовая','vi':'Hồng'},
    'sunset':{'ko':'선셋','en':'Sunset','ja':'サンセット','zh':'日落','es':'Atardecer','fr':'Crépuscule','de':'Sonnenuntergang','pt':'Pôr do sol','ru':'Закат','vi':'Hoàng hôn'},
    'forest':{'ko':'포레스트','en':'Forest','ja':'フォレスト','zh':'森林','es':'Bosque','fr':'Forêt','de':'Wald','pt':'Floresta','ru':'Лес','vi':'Rừng'},
    'monokai':{'ko':'모노카이','en':'Monokai','ja':'モノカイ','zh':'Monokai','es':'Monokai','fr':'Monokai','de':'Monokai','pt':'Monokai','ru':'Монокай','vi':'Monokai'},
}

THEMES = {
    'dark_purple':{
        'bg':'#0d1117','sb':'#161b22','card':'#1c2333','inp':'#0d1117',
        'hover':'#2d333b','acc':'#7c3aed','acc_d':'#6d28d9','acc_l':'#a78bfa',
        'tx':'#e6edf3','tx2':'#8b949e','brd':'#30363d','grn':'#3fb950',
        'red':'#f85149','yel':'#d29922','blu':'#58a6ff','overlay':'#0a0a12'},
    'light':{
        'bg':'#f0f2f5','sb':'#ffffff','card':'#ffffff','inp':'#f7f8fa',
        'hover':'#e8eaed','acc':'#7c3aed','acc_d':'#6d28d9','acc_l':'#9b6dff',
        'tx':'#1f2328','tx2':'#656d76','brd':'#d1d5db','grn':'#1a7f37',
        'red':'#cf222e','yel':'#9a6700','blu':'#0969da','overlay':'#e8e8ee'},
    'dark_blue':{
        'bg':'#0a192f','sb':'#112240','card':'#1d3461','inp':'#0a192f',
        'hover':'#233554','acc':'#64ffda','acc_d':'#4fd1c5','acc_l':'#9fffed',
        'tx':'#ccd6f6','tx2':'#8892b0','brd':'#233554','grn':'#64ffda',
        'red':'#ff6b6b','yel':'#ffd93d','blu':'#57cbff','overlay':'#060f1f'},
    'nord':{
        'bg':'#2e3440','sb':'#3b4252','card':'#434c5e','inp':'#2e3440',
        'hover':'#4c566a','acc':'#88c0d0','acc_d':'#81a1c1','acc_l':'#8fbcbb',
        'tx':'#eceff4','tx2':'#d8dee9','brd':'#4c566a','grn':'#a3be8c',
        'red':'#bf616a','yel':'#ebcb8b','blu':'#81a1c1','overlay':'#242933'},
    'rose':{
        'bg':'#1a1025','sb':'#231533','card':'#2d1f3d','inp':'#1a1025',
        'hover':'#3d2d52','acc':'#f472b6','acc_d':'#ec4899','acc_l':'#f9a8d4',
        'tx':'#f3e8ff','tx2':'#a78bbb','brd':'#3d2d52','grn':'#4ade80',
        'red':'#fb7185','yel':'#fbbf24','blu':'#60a5fa','overlay':'#120a1a'},
    'sunset':{
        'bg':'#1c1210','sb':'#2a1c18','card':'#352520','inp':'#1c1210',
        'hover':'#4a3830','acc':'#f97316','acc_d':'#ea580c','acc_l':'#fb923c',
        'tx':'#fef3c7','tx2':'#a8967c','brd':'#4a3830','grn':'#4ade80',
        'red':'#ef4444','yel':'#fbbf24','blu':'#60a5fa','overlay':'#140e0c'},
    'forest':{
        'bg':'#0f1a14','sb':'#162419','card':'#1e3025','inp':'#0f1a14',
        'hover':'#2d4a38','acc':'#10b981','acc_d':'#059669','acc_l':'#34d399',
        'tx':'#ecfdf5','tx2':'#86a896','brd':'#2d4a38','grn':'#34d399',
        'red':'#f87171','yel':'#fbbf24','blu':'#60a5fa','overlay':'#0a120e'},
    'monokai':{
        'bg':'#272822','sb':'#1e1f1c','card':'#3e3d32','inp':'#272822',
        'hover':'#49483e','acc':'#a6e22e','acc_d':'#8cc919','acc_l':'#c4ff4d',
        'tx':'#f8f8f2','tx2':'#75715e','brd':'#49483e','grn':'#a6e22e',
        'red':'#f92672','yel':'#e6db74','blu':'#66d9ef','overlay':'#1d1e19'},
}

# ═══════════ TRANSLATIONS ═══════════
_K = {
    'app_title':'Personal Manager',
    'nav_contacts':'연락처','nav_ledger':'가계부','nav_calendar':'달력',
    'nav_diary':'다이어리','nav_reminder':'리마인더','nav_settings':'설정',
    'add':'+ 추가','edit':'수정','delete':'삭제','save':'저장',
    'cancel':'취소','confirm':'확인','back':'← 뒤로','open':'열기',
    'confirm_delete':'정말 삭제하시겠습니까?','confirm_delete_short':'삭제하시겠습니까?',
    'confirm_delete_event':'일정을 삭제하시겠습니까?',
    'contacts_add_title':'연락처 추가','contacts_edit_title':'연락처 수정',
    'contacts_empty':'연락처가 없습니다.',
    'name':'이름','phone':'전화번호','nickname':'별명','email':'이메일','address':'주소',
    'name_required':'이름을 입력하세요.',
    'ledger_add_title':'가계부 추가','ledger_empty':'내역이 없습니다.',
    'all':'전체','income':'소득','expense':'지출',
    'type':'유형','amount':'금액','tag':'태그','custom_tag':'직접 입력:',
    'description':'설명','date_format':'날짜 (YYYY-MM-DD)',
    'amount_error':'올바른 금액을 입력하세요.','tag_required':'태그를 선택/입력하세요.',
    'summary':'소득: {inc}  |  지출: {exp}  |  잔액: {bal}',
    'currency_fmt':'{a}원',
    'days':'일,월,화,수,목,금,토',
    'months':'1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월',
    'month_year':'{year}년 {month}월',
    'add_event':'+ 일정','event_add_title':'일정 추가',
    'event_name':'일정명','allday':'종일 일정',
    'start':'시작 (YYYY-MM-DD)','end':'종료 (YYYY-MM-DD)',
    'location':'장소','attendees':'참석자',
    'no_events':'일정이 없습니다.','event_name_required':'일정명을 입력하세요.',
    'jump_date':'날짜 이동','year_label':'년도','month_label':'월',
    'schedule_of':'{date} 일정',
    'diary_edit_title':'다이어리 편집','diary_new_title':'새 다이어리',
    'diary_empty':'다이어리가 없습니다.',
    'title':'제목','date_label':'날짜 (YYYY-MM-DD)','content':'본문',
    'link_events':'연결할 일정:','link_ledger':'연결할 가계부:','link_contacts':'함께한 사람:',
    'title_required':'제목을 입력하세요.',
    'reminder_add_title':'리마인더 추가','reminder_edit_title':'리마인더 수정',
    'reminder_empty':'리마인더가 없습니다.',
    'deadline':'마감 기한 (YYYY-MM-DD HH:MM)','deadline_label':'마감 기한',
    'deadline_prefix':'마감','done':'완료','overdue':'D+{d} (기한 초과)','dday':'D-Day!',
    'settings_language':'언어 설정','settings_theme':'테마 설정',
    'settings_apply':'적용','current':'현재',
    'event_count':'+{n}건','linked_ev':'일정 {n}','linked_led':'가계부 {n}','linked_con':'인물 {n}',
}

_E = {
    'app_title':'Personal Manager',
    'nav_contacts':'Contacts','nav_ledger':'Ledger','nav_calendar':'Calendar',
    'nav_diary':'Diary','nav_reminder':'Reminders','nav_settings':'Settings',
    'add':'+ Add','edit':'Edit','delete':'Delete','save':'Save',
    'cancel':'Cancel','confirm':'OK','back':'← Back','open':'Open',
    'confirm_delete':'Are you sure you want to delete?','confirm_delete_short':'Delete this item?',
    'confirm_delete_event':'Delete this event?',
    'contacts_add_title':'Add Contact','contacts_edit_title':'Edit Contact',
    'contacts_empty':'No contacts yet.',
    'name':'Name','phone':'Phone','nickname':'Nickname','email':'Email','address':'Address',
    'name_required':'Please enter a name.',
    'ledger_add_title':'Add Entry','ledger_empty':'No entries yet.',
    'all':'All','income':'Income','expense':'Expense',
    'type':'Type','amount':'Amount','tag':'Tag','custom_tag':'Custom:',
    'description':'Description','date_format':'Date (YYYY-MM-DD)',
    'amount_error':'Please enter a valid amount.','tag_required':'Please select or enter a tag.',
    'summary':'Income: {inc}  |  Expense: {exp}  |  Balance: {bal}',
    'currency_fmt':'${a}',
    'days':'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    'months':'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',
    'month_year':'{month_name} {year}',
    'add_event':'+ Event','event_add_title':'Add Event',
    'event_name':'Event Name','allday':'All Day',
    'start':'Start (YYYY-MM-DD)','end':'End (YYYY-MM-DD)',
    'location':'Location','attendees':'Attendees',
    'no_events':'No events.','event_name_required':'Please enter an event name.',
    'jump_date':'Go to Date','year_label':'Year','month_label':'Month',
    'schedule_of':'Events on {date}',
    'diary_edit_title':'Edit Diary','diary_new_title':'New Diary',
    'diary_empty':'No diary entries.',
    'title':'Title','date_label':'Date (YYYY-MM-DD)','content':'Content',
    'link_events':'Link Events:','link_ledger':'Link Ledger:','link_contacts':'People:',
    'title_required':'Please enter a title.',
    'reminder_add_title':'Add Reminder','reminder_edit_title':'Edit Reminder',
    'reminder_empty':'No reminders.',
    'deadline':'Deadline (YYYY-MM-DD HH:MM)','deadline_label':'Deadline',
    'deadline_prefix':'Due','done':'Done','overdue':'D+{d} (Overdue)','dday':'D-Day!',
    'settings_language':'Language','settings_theme':'Theme',
    'settings_apply':'Apply','current':'Current',
    'event_count':'+{n} more','linked_ev':'Events {n}','linked_led':'Ledger {n}','linked_con':'People {n}',
}

_J = {
    'app_title':'Personal Manager',
    'nav_contacts':'連絡先','nav_ledger':'家計簿','nav_calendar':'カレンダー',
    'nav_diary':'日記','nav_reminder':'リマインダー','nav_settings':'設定',
    'add':'+ 追加','edit':'編集','delete':'削除','save':'保存',
    'cancel':'キャンセル','confirm':'確認','back':'← 戻る','open':'開く',
    'confirm_delete':'本当に削除しますか？','confirm_delete_short':'削除しますか？',
    'confirm_delete_event':'予定を削除しますか？',
    'contacts_add_title':'連絡先追加','contacts_edit_title':'連絡先編集',
    'contacts_empty':'連絡先がありません。',
    'name':'名前','phone':'電話番号','nickname':'ニックネーム','email':'メール','address':'住所',
    'name_required':'名前を入力してください。',
    'ledger_add_title':'項目追加','ledger_empty':'項目がありません。',
    'all':'全部','income':'収入','expense':'支出',
    'type':'種類','amount':'金額','tag':'タグ','custom_tag':'直接入力:',
    'description':'説明','date_format':'日付 (YYYY-MM-DD)',
    'amount_error':'正しい金額を入力してください。','tag_required':'タグを選択/入力してください。',
    'summary':'収入: {inc}  |  支出: {exp}  |  残高: {bal}',
    'currency_fmt':'¥{a}',
    'days':'日,月,火,水,木,金,土',
    'months':'1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
    'month_year':'{year}年 {month}月',
    'add_event':'+ 予定','event_add_title':'予定追加',
    'event_name':'予定名','allday':'終日',
    'start':'開始 (YYYY-MM-DD)','end':'終了 (YYYY-MM-DD)',
    'location':'場所','attendees':'参加者',
    'no_events':'予定がありません。','event_name_required':'予定名を入力してください。',
    'jump_date':'日付移動','year_label':'年','month_label':'月',
    'schedule_of':'{date} の予定',
    'diary_edit_title':'日記編集','diary_new_title':'新しい日記',
    'diary_empty':'日記がありません。',
    'title':'タイトル','date_label':'日付 (YYYY-MM-DD)','content':'本文',
    'link_events':'関連予定:','link_ledger':'関連家計簿:','link_contacts':'関連人物:',
    'title_required':'タイトルを入力してください。',
    'reminder_add_title':'リマインダー追加','reminder_edit_title':'リマインダー編集',
    'reminder_empty':'リマインダーがありません。',
    'deadline':'期限 (YYYY-MM-DD HH:MM)','deadline_label':'期限',
    'deadline_prefix':'期限','done':'完了','overdue':'D+{d} (期限超過)','dday':'D-Day!',
    'settings_language':'言語設定','settings_theme':'テーマ設定',
    'settings_apply':'適用','current':'現在',
    'event_count':'+{n}件','linked_ev':'予定 {n}','linked_led':'家計簿 {n}','linked_con':'人物 {n}',
}

_Z = {
    'app_title':'Personal Manager',
    'nav_contacts':'联系人','nav_ledger':'账本','nav_calendar':'日历',
    'nav_diary':'日记','nav_reminder':'提醒','nav_settings':'设置',
    'add':'+ 添加','edit':'编辑','delete':'删除','save':'保存',
    'cancel':'取消','confirm':'确认','back':'← 返回','open':'打开',
    'confirm_delete':'确定要删除吗？','confirm_delete_short':'删除此项？',
    'confirm_delete_event':'删除此日程？',
    'contacts_add_title':'添加联系人','contacts_edit_title':'编辑联系人',
    'contacts_empty':'暂无联系人。',
    'name':'姓名','phone':'电话','nickname':'昵称','email':'邮箱','address':'地址',
    'name_required':'请输入姓名。',
    'ledger_add_title':'添加记录','ledger_empty':'暂无记录。',
    'all':'全部','income':'收入','expense':'支出',
    'type':'类型','amount':'金额','tag':'标签','custom_tag':'自定义:',
    'description':'描述','date_format':'日期 (YYYY-MM-DD)',
    'amount_error':'请输入有效金额。','tag_required':'请选择或输入标签。',
    'summary':'收入: {inc}  |  支出: {exp}  |  余额: {bal}',
    'currency_fmt':'¥{a}',
    'days':'日,一,二,三,四,五,六',
    'months':'1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
    'month_year':'{year}年 {month}月',
    'add_event':'+ 日程','event_add_title':'添加日程',
    'event_name':'日程名','allday':'全天',
    'start':'开始 (YYYY-MM-DD)','end':'结束 (YYYY-MM-DD)',
    'location':'地点','attendees':'参与者',
    'no_events':'暂无日程。','event_name_required':'请输入日程名。',
    'jump_date':'跳转日期','year_label':'年','month_label':'月',
    'schedule_of':'{date} 日程',
    'diary_edit_title':'编辑日记','diary_new_title':'新日记',
    'diary_empty':'暂无日记。',
    'title':'标题','date_label':'日期 (YYYY-MM-DD)','content':'正文',
    'link_events':'关联日程:','link_ledger':'关联账本:','link_contacts':'相关人物:',
    'title_required':'请输入标题。',
    'reminder_add_title':'添加提醒','reminder_edit_title':'编辑提醒',
    'reminder_empty':'暂无提醒。',
    'deadline':'截止 (YYYY-MM-DD HH:MM)','deadline_label':'截止日期',
    'deadline_prefix':'截止','done':'完成','overdue':'D+{d} (已逾期)','dday':'D-Day!',
    'settings_language':'语言设置','settings_theme':'主题设置',
    'settings_apply':'应用','current':'当前',
    'event_count':'+{n}项','linked_ev':'日程 {n}','linked_led':'账本 {n}','linked_con':'人物 {n}',
}

_ES = {
    'app_title':'Personal Manager',
    'nav_contacts':'Contactos','nav_ledger':'Contabilidad','nav_calendar':'Calendario',
    'nav_diary':'Diario','nav_reminder':'Recordatorios','nav_settings':'Ajustes',
    'add':'+ Añadir','edit':'Editar','delete':'Eliminar','save':'Guardar',
    'cancel':'Cancelar','confirm':'Aceptar','back':'← Atrás','open':'Abrir',
    'confirm_delete':'¿Seguro que desea eliminar?','confirm_delete_short':'¿Eliminar este elemento?',
    'confirm_delete_event':'¿Eliminar este evento?',
    'contacts_add_title':'Añadir Contacto','contacts_edit_title':'Editar Contacto',
    'contacts_empty':'No hay contactos.',
    'name':'Nombre','phone':'Teléfono','nickname':'Apodo','email':'Email','address':'Dirección',
    'name_required':'Ingrese un nombre.',
    'ledger_add_title':'Añadir Registro','ledger_empty':'No hay registros.',
    'all':'Todo','income':'Ingreso','expense':'Gasto',
    'type':'Tipo','amount':'Monto','tag':'Etiqueta','custom_tag':'Personalizado:',
    'description':'Descripción','date_format':'Fecha (YYYY-MM-DD)',
    'amount_error':'Ingrese un monto válido.','tag_required':'Seleccione o ingrese una etiqueta.',
    'summary':'Ingreso: {inc}  |  Gasto: {exp}  |  Saldo: {bal}',
    'currency_fmt':'€{a}',
    'days':'Dom,Lun,Mar,Mié,Jue,Vie,Sáb',
    'months':'Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic',
    'month_year':'{month_name} {year}',
    'add_event':'+ Evento','event_add_title':'Añadir Evento',
    'event_name':'Nombre del evento','allday':'Todo el día',
    'start':'Inicio (YYYY-MM-DD)','end':'Fin (YYYY-MM-DD)',
    'location':'Lugar','attendees':'Asistentes',
    'no_events':'No hay eventos.','event_name_required':'Ingrese un nombre de evento.',
    'jump_date':'Ir a fecha','year_label':'Año','month_label':'Mes',
    'schedule_of':'Eventos del {date}',
    'diary_edit_title':'Editar Diario','diary_new_title':'Nuevo Diario',
    'diary_empty':'No hay entradas.',
    'title':'Título','date_label':'Fecha (YYYY-MM-DD)','content':'Contenido',
    'link_events':'Vincular eventos:','link_ledger':'Vincular registros:','link_contacts':'Personas:',
    'title_required':'Ingrese un título.',
    'reminder_add_title':'Añadir Recordatorio','reminder_edit_title':'Editar Recordatorio',
    'reminder_empty':'No hay recordatorios.',
    'deadline':'Fecha límite (YYYY-MM-DD HH:MM)','deadline_label':'Fecha límite',
    'deadline_prefix':'Límite','done':'Hecho','overdue':'D+{d} (Vencido)','dday':'D-Day!',
    'settings_language':'Idioma','settings_theme':'Tema',
    'settings_apply':'Aplicar','current':'Actual',
    'event_count':'+{n} más','linked_ev':'Eventos {n}','linked_led':'Registros {n}','linked_con':'Personas {n}',
}

_FR = {
    'app_title':'Personal Manager',
    'nav_contacts':'Contacts','nav_ledger':'Comptabilité','nav_calendar':'Calendrier',
    'nav_diary':'Journal','nav_reminder':'Rappels','nav_settings':'Paramètres',
    'add':'+ Ajouter','edit':'Modifier','delete':'Supprimer','save':'Enregistrer',
    'cancel':'Annuler','confirm':'OK','back':'← Retour','open':'Ouvrir',
    'confirm_delete':'Voulez-vous vraiment supprimer ?','confirm_delete_short':'Supprimer ?',
    'confirm_delete_event':'Supprimer cet événement ?',
    'contacts_add_title':'Ajouter Contact','contacts_edit_title':'Modifier Contact',
    'contacts_empty':'Aucun contact.',
    'name':'Nom','phone':'Téléphone','nickname':'Surnom','email':'E-mail','address':'Adresse',
    'name_required':'Veuillez entrer un nom.',
    'ledger_add_title':'Ajouter Entrée','ledger_empty':'Aucune entrée.',
    'all':'Tout','income':'Revenu','expense':'Dépense',
    'type':'Type','amount':'Montant','tag':'Étiquette','custom_tag':'Personnalisé :',
    'description':'Description','date_format':'Date (YYYY-MM-DD)',
    'amount_error':'Montant invalide.','tag_required':'Sélectionnez ou entrez une étiquette.',
    'summary':'Revenu: {inc}  |  Dépense: {exp}  |  Solde: {bal}',
    'currency_fmt':'€{a}',
    'days':'Dim,Lun,Mar,Mer,Jeu,Ven,Sam',
    'months':'Jan,Fév,Mar,Avr,Mai,Jun,Jul,Aoû,Sep,Oct,Nov,Déc',
    'month_year':'{month_name} {year}',
    'add_event':'+ Événement','event_add_title':'Ajouter Événement',
    'event_name':'Nom','allday':'Journée entière',
    'start':'Début (YYYY-MM-DD)','end':'Fin (YYYY-MM-DD)',
    'location':'Lieu','attendees':'Participants',
    'no_events':'Aucun événement.','event_name_required':'Entrez un nom d\'événement.',
    'jump_date':'Aller à la date','year_label':'Année','month_label':'Mois',
    'schedule_of':'Événements du {date}',
    'diary_edit_title':'Modifier Journal','diary_new_title':'Nouveau Journal',
    'diary_empty':'Aucune entrée.',
    'title':'Titre','date_label':'Date (YYYY-MM-DD)','content':'Contenu',
    'link_events':'Lier événements :','link_ledger':'Lier comptabilité :','link_contacts':'Personnes :',
    'title_required':'Veuillez entrer un titre.',
    'reminder_add_title':'Ajouter Rappel','reminder_edit_title':'Modifier Rappel',
    'reminder_empty':'Aucun rappel.',
    'deadline':'Échéance (YYYY-MM-DD HH:MM)','deadline_label':'Échéance',
    'deadline_prefix':'Échéance','done':'Terminé','overdue':'D+{d} (En retard)','dday':'Jour J !',
    'settings_language':'Langue','settings_theme':'Thème',
    'settings_apply':'Appliquer','current':'Actuel',
    'event_count':'+{n} de plus','linked_ev':'Événements {n}','linked_led':'Comptabilité {n}','linked_con':'Personnes {n}',
}

_DE = {
    'app_title':'Personal Manager',
    'nav_contacts':'Kontakte','nav_ledger':'Haushaltsbuch','nav_calendar':'Kalender',
    'nav_diary':'Tagebuch','nav_reminder':'Erinnerungen','nav_settings':'Einstellungen',
    'add':'+ Hinzufügen','edit':'Bearbeiten','delete':'Löschen','save':'Speichern',
    'cancel':'Abbrechen','confirm':'OK','back':'← Zurück','open':'Öffnen',
    'confirm_delete':'Wirklich löschen?','confirm_delete_short':'Diesen Eintrag löschen?',
    'confirm_delete_event':'Dieses Ereignis löschen?',
    'contacts_add_title':'Kontakt hinzufügen','contacts_edit_title':'Kontakt bearbeiten',
    'contacts_empty':'Keine Kontakte.',
    'name':'Name','phone':'Telefon','nickname':'Spitzname','email':'E-Mail','address':'Adresse',
    'name_required':'Bitte Name eingeben.',
    'ledger_add_title':'Eintrag hinzufügen','ledger_empty':'Keine Einträge.',
    'all':'Alle','income':'Einnahmen','expense':'Ausgaben',
    'type':'Typ','amount':'Betrag','tag':'Tag','custom_tag':'Benutzerdefiniert:',
    'description':'Beschreibung','date_format':'Datum (YYYY-MM-DD)',
    'amount_error':'Bitte gültigen Betrag eingeben.','tag_required':'Bitte Tag auswählen oder eingeben.',
    'summary':'Einnahmen: {inc}  |  Ausgaben: {exp}  |  Saldo: {bal}',
    'currency_fmt':'€{a}',
    'days':'So,Mo,Di,Mi,Do,Fr,Sa',
    'months':'Jan,Feb,Mär,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Dez',
    'month_year':'{month_name} {year}',
    'add_event':'+ Ereignis','event_add_title':'Ereignis hinzufügen',
    'event_name':'Ereignisname','allday':'Ganztägig',
    'start':'Beginn (YYYY-MM-DD)','end':'Ende (YYYY-MM-DD)',
    'location':'Ort','attendees':'Teilnehmer',
    'no_events':'Keine Ereignisse.','event_name_required':'Bitte Ereignisname eingeben.',
    'jump_date':'Gehe zu Datum','year_label':'Jahr','month_label':'Monat',
    'schedule_of':'Ereignisse am {date}',
    'diary_edit_title':'Tagebuch bearbeiten','diary_new_title':'Neues Tagebuch',
    'diary_empty':'Keine Einträge.',
    'title':'Titel','date_label':'Datum (YYYY-MM-DD)','content':'Inhalt',
    'link_events':'Verknüpfte Ereignisse:','link_ledger':'Verknüpfte Einträge:','link_contacts':'Personen:',
    'title_required':'Bitte Titel eingeben.',
    'reminder_add_title':'Erinnerung hinzufügen','reminder_edit_title':'Erinnerung bearbeiten',
    'reminder_empty':'Keine Erinnerungen.',
    'deadline':'Frist (YYYY-MM-DD HH:MM)','deadline_label':'Frist',
    'deadline_prefix':'Frist','done':'Erledigt','overdue':'D+{d} (Überfällig)','dday':'D-Day!',
    'settings_language':'Sprache','settings_theme':'Design',
    'settings_apply':'Anwenden','current':'Aktuell',
    'event_count':'+{n} mehr','linked_ev':'Ereignisse {n}','linked_led':'Einträge {n}','linked_con':'Personen {n}',
}

_PT = {
    'app_title':'Personal Manager',
    'nav_contacts':'Contatos','nav_ledger':'Finanças','nav_calendar':'Calendário',
    'nav_diary':'Diário','nav_reminder':'Lembretes','nav_settings':'Configurações',
    'add':'+ Adicionar','edit':'Editar','delete':'Excluir','save':'Salvar',
    'cancel':'Cancelar','confirm':'OK','back':'← Voltar','open':'Abrir',
    'confirm_delete':'Tem certeza que deseja excluir?','confirm_delete_short':'Excluir este item?',
    'confirm_delete_event':'Excluir este evento?',
    'contacts_add_title':'Adicionar Contato','contacts_edit_title':'Editar Contato',
    'contacts_empty':'Nenhum contato.',
    'name':'Nome','phone':'Telefone','nickname':'Apelido','email':'E-mail','address':'Endereço',
    'name_required':'Insira um nome.',
    'ledger_add_title':'Adicionar Registro','ledger_empty':'Nenhum registro.',
    'all':'Tudo','income':'Receita','expense':'Despesa',
    'type':'Tipo','amount':'Valor','tag':'Tag','custom_tag':'Personalizado:',
    'description':'Descrição','date_format':'Data (YYYY-MM-DD)',
    'amount_error':'Insira um valor válido.','tag_required':'Selecione ou insira uma tag.',
    'summary':'Receita: {inc}  |  Despesa: {exp}  |  Saldo: {bal}',
    'currency_fmt':'R${a}',
    'days':'Dom,Seg,Ter,Qua,Qui,Sex,Sáb',
    'months':'Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez',
    'month_year':'{month_name} {year}',
    'add_event':'+ Evento','event_add_title':'Adicionar Evento',
    'event_name':'Nome do evento','allday':'Dia inteiro',
    'start':'Início (YYYY-MM-DD)','end':'Fim (YYYY-MM-DD)',
    'location':'Local','attendees':'Participantes',
    'no_events':'Nenhum evento.','event_name_required':'Insira o nome do evento.',
    'jump_date':'Ir para data','year_label':'Ano','month_label':'Mês',
    'schedule_of':'Eventos em {date}',
    'diary_edit_title':'Editar Diário','diary_new_title':'Novo Diário',
    'diary_empty':'Nenhuma entrada.',
    'title':'Título','date_label':'Data (YYYY-MM-DD)','content':'Conteúdo',
    'link_events':'Vincular eventos:','link_ledger':'Vincular finanças:','link_contacts':'Pessoas:',
    'title_required':'Insira um título.',
    'reminder_add_title':'Adicionar Lembrete','reminder_edit_title':'Editar Lembrete',
    'reminder_empty':'Nenhum lembrete.',
    'deadline':'Prazo (YYYY-MM-DD HH:MM)','deadline_label':'Prazo',
    'deadline_prefix':'Prazo','done':'Concluído','overdue':'D+{d} (Atrasado)','dday':'D-Day!',
    'settings_language':'Idioma','settings_theme':'Tema',
    'settings_apply':'Aplicar','current':'Atual',
    'event_count':'+{n} mais','linked_ev':'Eventos {n}','linked_led':'Finanças {n}','linked_con':'Pessoas {n}',
}

_RU = {
    'app_title':'Personal Manager',
    'nav_contacts':'Контакты','nav_ledger':'Финансы','nav_calendar':'Календарь',
    'nav_diary':'Дневник','nav_reminder':'Напоминания','nav_settings':'Настройки',
    'add':'+ Добавить','edit':'Изменить','delete':'Удалить','save':'Сохранить',
    'cancel':'Отмена','confirm':'ОК','back':'← Назад','open':'Открыть',
    'confirm_delete':'Вы уверены, что хотите удалить?','confirm_delete_short':'Удалить?',
    'confirm_delete_event':'Удалить событие?',
    'contacts_add_title':'Добавить контакт','contacts_edit_title':'Изменить контакт',
    'contacts_empty':'Нет контактов.',
    'name':'Имя','phone':'Телефон','nickname':'Псевдоним','email':'Почта','address':'Адрес',
    'name_required':'Введите имя.',
    'ledger_add_title':'Добавить запись','ledger_empty':'Нет записей.',
    'all':'Все','income':'Доход','expense':'Расход',
    'type':'Тип','amount':'Сумма','tag':'Тег','custom_tag':'Свой:',
    'description':'Описание','date_format':'Дата (YYYY-MM-DD)',
    'amount_error':'Введите корректную сумму.','tag_required':'Выберите или введите тег.',
    'summary':'Доход: {inc}  |  Расход: {exp}  |  Баланс: {bal}',
    'currency_fmt':'₽{a}',
    'days':'Вс,Пн,Вт,Ср,Чт,Пт,Сб',
    'months':'Янв,Фев,Мар,Апр,Май,Июн,Июл,Авг,Сен,Окт,Ноя,Дек',
    'month_year':'{month_name} {year}',
    'add_event':'+ Событие','event_add_title':'Добавить событие',
    'event_name':'Название','allday':'Весь день',
    'start':'Начало (YYYY-MM-DD)','end':'Конец (YYYY-MM-DD)',
    'location':'Место','attendees':'Участники',
    'no_events':'Нет событий.','event_name_required':'Введите название.',
    'jump_date':'Перейти к дате','year_label':'Год','month_label':'Месяц',
    'schedule_of':'События {date}',
    'diary_edit_title':'Редактировать','diary_new_title':'Новая запись',
    'diary_empty':'Нет записей.',
    'title':'Заголовок','date_label':'Дата (YYYY-MM-DD)','content':'Содержание',
    'link_events':'Связать события:','link_ledger':'Связать финансы:','link_contacts':'Люди:',
    'title_required':'Введите заголовок.',
    'reminder_add_title':'Добавить напоминание','reminder_edit_title':'Изменить напоминание',
    'reminder_empty':'Нет напоминаний.',
    'deadline':'Срок (YYYY-MM-DD HH:MM)','deadline_label':'Срок',
    'deadline_prefix':'Срок','done':'Готово','overdue':'D+{d} (Просрочено)','dday':'D-Day!',
    'settings_language':'Язык','settings_theme':'Тема',
    'settings_apply':'Применить','current':'Текущий',
    'event_count':'+{n} ещё','linked_ev':'События {n}','linked_led':'Финансы {n}','linked_con':'Люди {n}',
}

_VI = {
    'app_title':'Personal Manager',
    'nav_contacts':'Danh bạ','nav_ledger':'Sổ chi tiêu','nav_calendar':'Lịch',
    'nav_diary':'Nhật ký','nav_reminder':'Nhắc nhở','nav_settings':'Cài đặt',
    'add':'+ Thêm','edit':'Sửa','delete':'Xóa','save':'Lưu',
    'cancel':'Hủy','confirm':'OK','back':'← Quay lại','open':'Mở',
    'confirm_delete':'Bạn có chắc muốn xóa?','confirm_delete_short':'Xóa mục này?',
    'confirm_delete_event':'Xóa sự kiện này?',
    'contacts_add_title':'Thêm liên hệ','contacts_edit_title':'Sửa liên hệ',
    'contacts_empty':'Chưa có liên hệ.',
    'name':'Tên','phone':'Điện thoại','nickname':'Biệt danh','email':'Email','address':'Địa chỉ',
    'name_required':'Vui lòng nhập tên.',
    'ledger_add_title':'Thêm mục','ledger_empty':'Chưa có mục nào.',
    'all':'Tất cả','income':'Thu nhập','expense':'Chi tiêu',
    'type':'Loại','amount':'Số tiền','tag':'Nhãn','custom_tag':'Tùy chỉnh:',
    'description':'Mô tả','date_format':'Ngày (YYYY-MM-DD)',
    'amount_error':'Vui lòng nhập số tiền hợp lệ.','tag_required':'Vui lòng chọn hoặc nhập nhãn.',
    'summary':'Thu: {inc}  |  Chi: {exp}  |  Còn: {bal}',
    'currency_fmt':'{a}₫',
    'days':'CN,T2,T3,T4,T5,T6,T7',
    'months':'Th1,Th2,Th3,Th4,Th5,Th6,Th7,Th8,Th9,Th10,Th11,Th12',
    'month_year':'{month_name} {year}',
    'add_event':'+ Sự kiện','event_add_title':'Thêm sự kiện',
    'event_name':'Tên sự kiện','allday':'Cả ngày',
    'start':'Bắt đầu (YYYY-MM-DD)','end':'Kết thúc (YYYY-MM-DD)',
    'location':'Địa điểm','attendees':'Người tham dự',
    'no_events':'Không có sự kiện.','event_name_required':'Vui lòng nhập tên sự kiện.',
    'jump_date':'Đến ngày','year_label':'Năm','month_label':'Tháng',
    'schedule_of':'Sự kiện {date}',
    'diary_edit_title':'Sửa nhật ký','diary_new_title':'Nhật ký mới',
    'diary_empty':'Chưa có nhật ký.',
    'title':'Tiêu đề','date_label':'Ngày (YYYY-MM-DD)','content':'Nội dung',
    'link_events':'Liên kết sự kiện:','link_ledger':'Liên kết chi tiêu:','link_contacts':'Người liên quan:',
    'title_required':'Vui lòng nhập tiêu đề.',
    'reminder_add_title':'Thêm nhắc nhở','reminder_edit_title':'Sửa nhắc nhở',
    'reminder_empty':'Chưa có nhắc nhở.',
    'deadline':'Hạn (YYYY-MM-DD HH:MM)','deadline_label':'Hạn chót',
    'deadline_prefix':'Hạn','done':'Hoàn thành','overdue':'D+{d} (Quá hạn)','dday':'D-Day!',
    'settings_language':'Ngôn ngữ','settings_theme':'Giao diện',
    'settings_apply':'Áp dụng','current':'Hiện tại',
    'event_count':'+{n} nữa','linked_ev':'Sự kiện {n}','linked_led':'Chi tiêu {n}','linked_con':'Người {n}',
}

TRANSLATIONS = {'ko':_K,'en':_E,'ja':_J,'zh':_Z,'es':_ES,'fr':_FR,'de':_DE,'pt':_PT,'ru':_RU,'vi':_VI}

# ═══════════ STATE & HELPERS ═══════════
_lang = 'ko'
_theme = 'dark_purple'

def t(key):
    return TRANSLATIONS.get(_lang, _K).get(key, _K.get(key, key))

def get_colors():
    return dict(THEMES.get(_theme, THEMES['dark_purple']))

def get_theme_name(theme_key, lang=None):
    l = lang or _lang
    m = THEME_META.get(theme_key, {})
    return m.get(l, m.get('en', theme_key))

def set_lang(lang):
    global _lang
    if lang in TRANSLATIONS: _lang = lang

def set_theme(theme):
    global _theme
    if theme in THEMES: _theme = theme

def get_lang(): return _lang
def get_theme(): return _theme

def fmt_money(amount):
    return t('currency_fmt').replace('{a}', f'{amount:,.0f}')

def get_days():
    return t('days').split(',')

def get_months():
    return t('months').split(',')

def fmt_month_year(year, month):
    s = t('month_year')
    mn = get_months()[month-1]
    return s.replace('{year}', str(year)).replace('{month}', str(month)).replace('{month_name}', mn)
